# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: petardragicevic
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: back

provider:
  name: aws
  runtime: python3.12
  region: eu-central-1
  environment:
    ARTISTS_TABLE: ${self:service}-artists
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-artists"
  httpApi:
    cors:
      allowedOrigins:        
        - '*'                        # Dozvoljava POST metodu i Preflight OPTIONS metod
      allowedMethods: 
        - 'GET'
        - 'POST'
        - 'OPTIONS'                 # Dozvoljava slanje Content-Type i Authorization headera (potrebno za JSON i JWT)
      allowedHeaders: 
        - 'Content-Type'
        - 'Authorization'
      maxAge: 600                    # Opcionalno: Keširanje preflight odgovora na 10 minuta (600 sekundi)
    authorizers:
      # bouncer:
      #     identitySource: $request.header.Authorization
      #     issuerUrl: 
      #       Fn::sub: https://cognito-idp.${self:provider.region}.amazonaws.com/${CognitoUserPool}
      #     audience:
      #       - !Ref CognitoUserPoolClientWeb 
     # Authorizer - ne dozvoljava pristup lambda funkcijama ako je access token validan!
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !Sub "https://cognito-idp.${self:provider.region}.amazonaws.com/${CognitoUserPool}"
        audience:
          - !Ref CognitoUserPoolClientWeb

functions:
  preRegistration:
    handler: handlers/auth.preSignUp
    events:
      - cognitoUserPool:
          pool: MapsterUserPool
          trigger: PreSignUp

  postConfirmation:
    handler: handlers/auth.postConfirmation
    events:
      - cognitoUserPool:
          pool: MapsterUserPool
          trigger: PostConfirmation

  createArtist:
    handler: handlers.artist-creation.lambda_handler
    events:
      - httpApi:
          path: /artists
          method: post
        
     

resources:
  Resources:

    ArtistsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-artists
        AttributeDefinitions:
          - AttributeName: artistId
            AttributeType: S
        KeySchema:
          - AttributeName: artistId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    #region Cognito

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: MapsterUserPool
        UsernameAttributes: [email]
        AutoVerifiedAttributes: [email]
#        SelfSignUpEnabled: true
#        AccountRecoverySetting:
#          RecoveryMechanisms: []

        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false

        Schema:
          - Name: given_name
            AttributeDataType: String
            Required: true
            Mutable: true
          - Name: family_name
            AttributeDataType: String
            Required: true
            Mutable: true
          - Name: email
            AttributeDataType: String
            Required: true
            Mutable: false
          - Name: birthdate
            AttributeDataType: String
            Required: true
            Mutable: true

        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: true
            RequireUppercase: false
            RequireNumbers: false
            RequireSymbols: false

    AdminGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: Admin
        UserPoolId: !Ref CognitoUserPool
        Description: "Mapster administrators group"
        Precedence: 1

    UserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: User
        UserPoolId: !Ref CognitoUserPool
        Description: "Mapster regular users group"
        Precedence: 10

    CognitoUserPoolClientWeb:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: MapsterWebClient
        UserPoolId: !Ref CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        PreventUserExistenceErrors: ENABLED

    #endregion
