# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: petardragicevic
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: back

provider:
  name: aws
  runtime: python3.12
  region: eu-central-1
  environment:
    ARTISTS_TABLE: ${self:service}-artists
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-artists"

functions:
  createArtist:
    handler: handlers/artist/create.lambda_handler
    events:
      - http:
          path: artists
          method: post
          cors: true


resources:
  Resources:
    ArtistsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-artists
        AttributeDefinitions:
          - AttributeName: artistId
            AttributeType: S
        KeySchema:
          - AttributeName: artistId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST